# Generated by Django 4.1.7 on 2023-03-12 14:35

from django.db import migrations
from django.contrib.auth import get_user_model


def create(_apps, _schemas_editor):
    get_user_model().objects.create_superuser(
        is_staff=True,
        username='admin',
        password='admin'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create)
    ]
