# Generated by Django 4.1.7 on 2023-03-12 14:51

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth.models import (
    Permission,
    Group
)


def add_perm(grp, codename):
    content_type = ContentType.objects.get_for_model(get_user_model())
    perm = Permission.objects.create(
        codename=codename,
        name=codename,
        content_type=content_type
    )
    grp.permissions.add(perm)


def create_group(_apps, _schema_editor):
    management = Group.objects.create(name='ManagementTeam')
    sales = Group.objects.create(name='SalesTeam')
    support = Group.objects.create(name='SupportTeam')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_init_admin'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
