# Generated by Django 4.1.7 on 2023-03-12 14:51

from django.db import migrations, transaction
from django.contrib.contenttypes.models import ContentType
from crm.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.models import (
    Permission,
    Group
)


def add_perm(grp, codename):
    content_type = ContentType.objects.get_for_model(User)
    perm, _ = Permission.objects.get_or_create(
        codename=codename,
        name=codename,
        content_type=content_type
    )
    grp.permissions.add(perm)


def crud(grp, name):
    add_perm(grp, f'add_{name}')
    add_perm(grp, f'view_{name}')
    add_perm(grp, f'change_{name}')
    add_perm(grp, f'delete_{name}')


def read_only(grp, name):
    add_perm(grp, f'view_{name}')


def create_group(_apps, _schema_editor):
    with transaction.atomic():
        management = Group.objects.create(name='ManagementTeam')
        management.permissions.set([])
        add_perm(management, 'grant_user')
        crud(management, 'user')
        crud(management, 'event')
        crud(management, 'customer')
        crud(management, 'contract')

        sales = Group.objects.create(name='SalesTeam')
        sales.permissions.set([])
        crud(sales, 'customer')
        crud(sales, 'contract')
        crud(sales, 'event')

        support = Group.objects.create(name='SupportTeam')
        support.permissions.set([])
        read_only(support, 'customer')
        read_only(support, 'contract')

        add_perm(support, 'view_event')
        add_perm(support, 'change_event')
        add_perm(support, 'delete_event')

        management.user_set.add(get_user_model().objects.get(username="admin"))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_init_admin'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
