# Generated by Django 4.1.7 on 2023-03-12 14:51

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from crm.models import User
from django.contrib.auth.models import (
    Permission,
    Group
)


def add_perm(grp, codename):
    content_type = ContentType.objects.get_for_model(User)
    perm = Permission.objects.create(
        codename=codename,
        name=codename,
        content_type=content_type
    )
    grp.permissions.add(perm)


def all_perms(grp, name):
    add_perm(grp, f'add_{name}')
    add_perm(grp, f'view_{name}')
    add_perm(grp, f'change_{name}')
    add_perm(grp, f'delete_{name}')


def create_group(_apps, _schema_editor):
    management = Group.objects.create(name='ManagementTeam')
    management.permissions.set([])
    all_perms(management, 'user')

    sales = Group.objects.create(name='SalesTeam')
    sales.permissions.set([])

    support = Group.objects.create(name='SupportTeam')
    support.permissions.set([])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_init_admin'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
