# Generated by Django 4.1.7 on 2023-03-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sales_contact',
        ),
    ]
