# Generated by Django 4.1.7 on 2023-03-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_contract_sales_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractstatus',
            options={'verbose_name_plural': 'Contract status'},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name_plural': 'Event status'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
